sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - libssl-dev
    - libevent-dev
    - libexpat-dev
    - clang
script:
  - ./configure --enable-debug --disable-flto
  - make
  - make test
  - ./testbound -p ./testdata/rpz_respip.rpl
  - (cd testdata/clang-analysis.tdir; bash clang-analysis.test)
