sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - libssl-dev
    - libevent-dev
    - libexpat-dev
    - clang
script:
  - ./configure --enable-debug --disable-flto
  - make
  - make test
  - (cd testdata; ../testcode/mini_tdir.sh exe clang-analysis.tdir ; if grep -e "warning:" -e "error:" result.clang-analysis ; then exit 1; else exit 0; fi)
