name: Analysis and Ports

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Start analysis and port workflow'
        default: 'yes'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: GCC on Linux
            os: ubuntu-latest
            config: --enable-debug --disable-flto
            make_test: yes
          - name: Clang on Linux, clang-analysis
            os: ubuntu-latest
            config: "CC=clang --enable-debug --disable-flto"
            make_test: "yes"
            clang_analysis: "yes"
 
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - name: checks
        run: |
          echo ${{ matrix.config }}
          echo ${{ matrix.make_test }}
          echo ${{ matrix.clang_analysis }}
      - name: configure
        run: ./configure ${{ matrix.config }}
      - name: make
        run: make
      - name: make test
        if: ${{ matrix.make_test == 'yes' }}
        run: make test
      - name: clang-analysis
        if: ${{ matrix.clang_analysis == 'yes' }}
        run: (cd testdata/clang-analysis.tdir; bash clang-analysis.test)
