name: Analysis and Ports

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Start analysis and port workflow'
        default: 'yes'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: GCC on Linux
            env:
              - CONFIG_OPTS: "--enable-debug --disable-flto"
              - MAKE_TEST: "yes"
          - os: ubuntu-latest
            name: Clang on Linux, clang-analysis
            env:
              - CONFIG_OPTS: "CC=clang --enable-debug --disable-flto"
              - MAKE_TEST: "yes"
              - TEST_ANALYZER: "yes"
 
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - name: checks
        run: |
          echo $CONFIG_OPTS
          echo $MAKE_TEST
          echo $TEST_ANALYZER
      - name: configure
        run: ./configure $CONFIG_OPTS
      - name: make
        run: make
      - name: make test
        run: |
          if [ "$MAKE_TEST" = "yes" ]; then
            make test
          fi
      - name: analyzer
        run: |
          if [ "$TEST_ANALYZER" = "yes" ]; then
            (cd testdata/clang-analysis.tdir; bash clang-analysis.test)
          fi
