name: Analysis and Ports

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Start analysis and port workflow'
        default: 'yes'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
# temporarily commented out to speed up build.
#          - name: GCC on Linux
#            os: ubuntu-latest
#            config: "--enable-debug --disable-flto"
#            make_test: "yes"
#          - name: Clang on Linux, clang-analysis
#            os: ubuntu-latest
#            config: "CC=clang --enable-debug --disable-flto"
#            make_test: "yes"
#            clang_analysis: "yes"
          - name: Clang on Linux, libevent, clang-analysis
            os: ubuntu-latest
            config: "CC=clang --enable-debug --disable-flto --with-libevent"
            make_test: "yes"
            clang_analysis: "yes"
#          - name: GCC on OS X
#            os: macos-latest
#            install_expat: "yes"
#            config: "--enable-debug --disable-flto --with-ssl=/usr/local/opt/openssl --with-libexpat=/usr/local/opt/expat"
#            make_test: "yes"
          - name: Clang on OS X
            os: macos-latest
            install_expat: "yes"
            config: "CC=clang --enable-debug --disable-flto --with-ssl=/usr/local/opt/openssl --with-libexpat=/usr/local/opt/expat"
            make_test: "yes"
            clang_analysis: "yes"
 
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - name: install expat
        if: ${{ matrix.install_expat == 'yes' }}
        run: brew install expat
      - name: configure
        run: ./configure ${{ matrix.config }}
      - name: make
        run: make
      - name: make test
        if: ${{ matrix.make_test == 'yes' }}
        run: make test
      - name: clang-analysis
        if: ${{ matrix.clang_analysis == 'yes' }}
        run: (cd testdata/clang-analysis.tdir; bash clang-analysis.test)
